export const questions = [
    {
        id: 1,
        q: "A particle moves in a circular path with uniform speed. Which of the following remains constant?",
        options: {
            A: "Velocity",
            B: "Acceleration",
            C: "Kinetic Energy",
            D: "Displacement",
        },
    },
    {
        id: 2,
        q: "A ball is dropped from a height of 20 m. What is its velocity just before hitting the ground? (g = 10 m/s²)",
        options: {
            A: "10 m/s",
            B: "20 m/s",
            C: "30 m/s",
            D: "40 m/s",
        },
    },
    {
        id: 3,
        q: "Which of the following statements is correct about the motion of a projectile fired at an angle?",
        options: {
            A: "The horizontal velocity remains constant.",
            B: "The acceleration is zero at the highest point.",
            C: "The vertical velocity remains constant.",
            D: "The trajectory is a straight line.",
        },
    },
    {
        id: 4,
        q: "A capacitor of capacitance 4 µF is connected to a 12V battery. What is the charge stored in it?",
        options: {
            A: "24 µC",
            B: "48 µC",
            C: "12 µC",
            D: "36 µC",
        },
    },
    {id: 5, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 6, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 7, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 8, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 9, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 10, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 11, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 12, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 13, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 14, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 15, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 16, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 17, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 18, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 19, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 20, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 21, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 22, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 23, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 24, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 25, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 26, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 27, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 28, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 29, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 30, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 31, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 32, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 33, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 34, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 35, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 36, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 37, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 38, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 39, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 40, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 41, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 42, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 43, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 44, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 45, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 46, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 47, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 48, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 49, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
    {id: 50, q: "The escape velocity from Earth is approximately:",options: {A: "7 km/s", B: "9.8 km/s", C: "11.2 km/s", D: "15 km/s", },},
];
